from __future__ import annotations

import argparse
import re
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from validation_contract import ROOT, build_checks, overall_status, run_command, status_for


REPORT = ROOT / "reports" / "validation.md"


def git_value(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args], cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False
    )
    return result.stdout.strip()


def summarize_output(output: str) -> str:
    for pattern in [
        r"eval score: .+",
        r"Ran \d+ tests? in .+",
        r".+ scan: pass",
        r"documentation links: pass",
        r"starter registry: pass.+",
        r"gitleaks .+",
        r"Python .+",
    ]:
        match = re.search(pattern, output, re.IGNORECASE)
        if match:
            return match.group(0)
    return output.splitlines()[-1] if output else "no output"


def main() -> None:
    parser = argparse.ArgumentParser(description="Write a validation report from the shared validation contract.")
    parser.add_argument("--output", type=Path, default=REPORT)
    args = parser.parse_args()
    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows: list[tuple[str, str, str, str]] = []
    for label, command in build_checks(ROOT):
        code, output = run_command(command, ROOT)
        rows.append((label, "`" + " ".join(command) + "`", status_for(label, code, output), summarize_output(output)))

    statuses = [row[2] for row in rows]
    git_sha = git_value(["rev-parse", "--short", "HEAD"]) or "unknown"
    git_branch = git_value(["branch", "--show-current"]) or "unknown"
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# Validation Report",
        "",
        "This report is generated by the same deterministic check contract as `make validate`.",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Generated at | {generated_at} |",
        f"| Git branch | `{git_branch}` |",
        f"| Git commit | `{git_sha}` |",
        f"| Overall status | {overall_status(statuses)} |",
        "",
        "## Check Results",
        "",
        "| Check | Command | Status | Evidence |",
        "|---|---|---|---|",
    ]
    for label, command, status, evidence in rows:
        lines.append(f"| {label} | {command} | {status} | {evidence.replace('|', '\\|')} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- This is public-safe practice evidence, not production certification.",
            "- A local gitleaks skip makes this report Incomplete; CI marks it Passed only after the preceding gitleaks action succeeds.",
            "- The golden-set eval is intentionally small and deterministic.",
        ]
    )
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if "Failed" in statuses:
        raise SystemExit("Validation report contains failing checks.")


if __name__ == "__main__":
    main()
