from __future__ import annotations

import os
import re
import subprocess
from datetime import UTC, datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "reports" / "validation.md"


COMMANDS = [
    ("starter setup", ["make", "-C", "starter-kits/faq-agent-lite", "setup"]),
    ("starter unit tests", ["make", "-C", "starter-kits/faq-agent-lite", "test"]),
    ("starter golden-set eval", ["make", "-C", "starter-kits/faq-agent-lite", "eval"]),
    ("repo unit tests", ["python3", "-m", "unittest", "discover", "-s", "tests"]),
    ("secret scan", ["bash", "scripts/check_no_secrets.sh"]),
    ("private-term scan", ["bash", "scripts/check_no_private_terms.sh"]),
    ("pii scan", ["bash", "scripts/check_no_pii.sh"]),
    ("public-link scan", ["bash", "scripts/check_public_links.sh"]),
    ("generated-artifact scan", ["bash", "scripts/check_no_generated_artifacts.sh"]),
    ("gitleaks wrapper", ["bash", "scripts/check_gitleaks.sh"]),
]


def run_command(command: list[str]) -> tuple[int, str]:
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    result = subprocess.run(
        command,
        cwd=ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    output = result.stdout.strip()
    output = output.replace(str(ROOT), ".")
    return result.returncode, output


def git_value(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.stdout.strip()


def summarize_output(output: str) -> str:
    for pattern in [
        r"eval score: .+",
        r"Ran \d+ tests? in .+",
        r".+ scan: pass",
        r"gitleaks .+",
        r"Python .+",
    ]:
        match = re.search(pattern, output, re.IGNORECASE)
        if match:
            return match.group(0)
    return output.splitlines()[-1] if output else "no output"


def main() -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, str, str, str]] = []

    for label, command in COMMANDS:
        code, output = run_command(command)
        status = "Passed" if code == 0 else "Failed"
        rows.append((label, "`" + " ".join(command) + "`", status, summarize_output(output)))

    failed = [row for row in rows if row[2] != "Passed"]
    git_sha = git_value(["rev-parse", "--short", "HEAD"]) or "unknown"
    git_branch = git_value(["branch", "--show-current"]) or "unknown"
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# Validation Report",
        "",
        "This report is generated by `make validate-report` from deterministic local checks.",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Generated at | {generated_at} |",
        f"| Git branch | `{git_branch}` |",
        f"| Git commit | `{git_sha}` |",
        f"| Overall status | {'Passed' if not failed else 'Failed'} |",
        "",
        "## Check Results",
        "",
        "| Check | Command | Status | Evidence |",
        "|---|---|---|---|",
    ]

    for label, command, status, evidence in rows:
        safe_evidence = evidence.replace("|", "\\|")
        lines.append(f"| {label} | {command} | {status} | {safe_evidence} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- This is public-safe practice evidence, not production certification.",
            "- The golden-set eval is intentionally small and deterministic.",
            "- GitHub Actions runs the same validation gate and uploads this report as an artifact.",
        ]
    )

    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if failed:
        raise SystemExit("Validation report contains failing checks.")


if __name__ == "__main__":
    main()
